# Crawl Data Twitter > 2000 Tweets
The crawling process was done using Tweet-Harvest. Written by Helmi Satria on  March 30th 2024.

In [ ]:
#@title Twitter Auth Token
# auth token ambil dari cookies parameter auth token
twitter_auth_token = 'fb53294ce80c28916acaa83dae2b909d6c337933' # change this auth token

In [ ]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [85.2 kB]
Get:8 https://cli.github.com/packages stable/main amd64 Packages [357 B]
Get:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease [24.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,824 kB]
Get:13 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [39.2 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [70.9 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,120 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,652 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,926 kB]
Get:18 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 Packages [75.3 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,877 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,613 kB]
Get:21 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,301 kB]
Get:22 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,780 kB]
Get:23 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [62.6 kB]
Fetched 37.9 MB in 4s (10.3 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
gnupg is already the newest version (2.2.27-3ubuntu2.5).
gnupg set to manually installed.
Suggested packages:
  libcurl4-doc libidn11-dev libldap2-dev librtmp-dev
The following packages will be upgraded:
  curl libcurl4 libcurl4-openssl-dev
3 upgraded, 0 newly installed, 0 to remove and 115 not upgraded.
Need to get 870 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4-openssl-dev amd64 7.81.0-1ubuntu1.22 [386 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 curl amd64 7.81.0-1ubuntu1.22 [194 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4 amd64 7.81.0-1ubuntu1.22 [290 kB]
Fetched 870 kB in 1s (987 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 3.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../libcurl4-openssl-dev_7.81.0-1ubuntu1.22_amd64.deb ...
Unpacking libcurl4-openssl-dev:amd64 (7.81.0-1ubuntu1.22) over (7.81.0-1ubuntu1.21) ...
Preparing to unpack .../curl_7.81.0-1ubuntu1.22_amd64.deb ...
Unpacking curl (7.81.0-1ubuntu1.22) over (7.81.0-1ubuntu1.21) ...
Preparing to unpack .../libcurl4_7.81.0-1ubuntu1.22_amd64.deb ...
Unpacking libcurl4:amd64 (7.81.0-1ubuntu1.22) over (7.81.0-1ubuntu1.21) ...
Setting up libcurl4:amd64 (7.81.0-1ubuntu1.22) ...
Setting up curl (7.81.0-1ubuntu1.22) ...
Setting up libcurl4-openssl-dev:amd64 (7.81.0-1ubuntu1.22) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://cli.github.com/packages stable InRelease
Get:3 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:8 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [14.0 kB]
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 26.1 kB in 1s (17.5 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 115 not upgraded.
Need to get 32.2 MB of archives.
After this operation, 196 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.20.1-1nodesource1 [32.2 MB]
Fetched 32.2 MB in 1s (53.9 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package nodejs.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../nodejs_20.20.1-1nodesource1_amd64.deb ...
Unpacking nodejs (20.20.1-1nodesource1) ...
Setting up nodejs (20.20.1-1nodesource1) ...
Processing triggers for man-db (2.10.2-1) ...

In [3]:
!apt-get update
!apt-get install -y \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libxkbcommon0 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  libgbm1 \
  libasound2 \
  libpangocairo-1.0-0 \
  libpango-1.0-0 \
  libcairo2 \
  libgtk-3-0

Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (3,395 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcairo2 is already the newest version (1.16.0-5ubuntu2).
libcairo2 set to manually installed.
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libcups2 is already the newest version (2.4.1op1-1ubuntu4.16).
libcups2 set to manually installed.
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
libpangocairo-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpangocairo-1.0-0 set to manually installed.
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libasound2-data libatk1.0-data
  libatspi2.0-0 libgtk-3-bin libgtk-3-common librsvg2-common libxtst6
  session-migration
Suggested packages:
  libasound2-plugins alsa-utils gvfs
Recommended packages:
  alsa-ucm-conf alsa-topology-conf
The following NEW packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libgtk-3-0 libgtk-3-bin libgtk-3-common
  librsvg2-common libxcomposite1 libxtst6 session-migration
The following packages will be upgraded:
  libasound2 libasound2-data
2 upgraded, 13 newly installed, 0 to remove and 113 not upgraded.
Need to get 4,107 kB of archives.
After this operation, 12.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2 amd64 1.2.6.1-1ubuntu1.1 [391 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2-data all 1.2.6.1-1ubuntu1.1 [19.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-common all 3.24.33-1ubuntu2.2 [239 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-0 amd64 3.24.33-1ubuntu2.2 [3,053 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-bin amd64 3.24.33-1ubuntu2.2 [69.6 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 librsvg2-common amd64 2.52.5+dfsg-3ubuntu0.2 [17.7 kB]
Fetched 4,107 kB in 1s (3,694 kB/s)
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 122903 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Preparing to unpack .../05-libasound2_1.2.6.1-1ubuntu1.1_amd64.deb ...
Unpacking libasound2:amd64 (1.2.6.1-1ubuntu1.1) over (1.2.6.1-1ubuntu1) ...
Preparing to unpack .../06-libasound2-data_1.2.6.1-1ubuntu1.1_all.deb ...
Unpacking libasound2-data (1.2.6.1-1ubuntu1.1) over (1.2.6.1-1ubuntu1) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../07-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../08-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../09-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../10-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libgtk-3-common.
Preparing to unpack .../11-libgtk-3-common_3.24.33-1ubuntu2.2_all.deb ...
Unpacking libgtk-3-common (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-0:amd64.
Preparing to unpack .../12-libgtk-3-0_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-bin.
Preparing to unpack .../13-libgtk-3-bin_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../14-librsvg2-common_2.52.5+dfsg-3ubuntu0.2_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libasound2-data (1.2.6.1-1ubuntu1.1) ...
Setting up librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libasound2:amd64 (1.2.6.1-1ubuntu1.1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up libgtk-3-common (3.24.33-1ubuntu2.2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.8+dfsg-1ubuntu0.4) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.7) ...
Setting up libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

Setting up libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Setting up at-spi2-core (2.44.0-3) ...

In [4]:
!npx playwright install chromium

⠙⠹⠸⠼⠴⠦⠧⠇Need to install the following packages:
playwright@1.58.2
Ok to proceed? (y) ^C

In [5]:
# Crawl Data

filename = 'filedataset.csv'
# search_keyword = 'from:detikcom lang:id since:2025-10-01 until:2026-02-30'
search_keyword = 'from:detikcom lang:id '
limit = 100

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
⠋npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
⠙npm warn deprecated glob@7.2.3: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: from:detikcom lang:id

 (3)Created new directory: /content/tweets-data


Your tweets saved to: /content/tweets-data/filedataset.csv
Total tweets saved: 20

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/filedataset.csv
Total tweets saved: 40


Your tweets saved to: /content/tweets-data/filedataset.csv
Total tweets saved: 60


Your tweets saved to: /content/tweets-data/filedataset.csv
Total tweets saved: 80

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/filedataset.csv
Total tweets saved: 100
Got 100 tweets, done scrolling...
⠙

In [8]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/filedataset.csv"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path)

df.to_csv('filedataset.csv', index=False)

# Display the DataFrame
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2027988901068177718,Sun Mar 01 06:06:46 +0000 2026,64,Iran membalas serangan AS-Israel dengan membom...,2027988901068177718,NaN,NaN,in,NaN,1,2,5,https://x.com/undefined/status/202798890106817...,69183155,NaN
1,2027973484236927204,Sun Mar 01 05:05:31 +0000 2026,64,Pemimpin tertinggi Iran Ali Khamenei dikabarka...,2027973484236927204,NaN,NaN,in,NaN,1,10,13,https://x.com/undefined/status/202797348423692...,69183155,NaN
2,2027946872758034525,Sun Mar 01 03:19:47 +0000 2026,176,Jangan lupa untuk ikutin syarat dan ketentuan ...,2027946875400429965,https://pbs.twimg.com/media/HCS27eGbcAAbpoj.jpg,detikcom,in,NaN,4,403,131,https://x.com/undefined/status/202794687540042...,69183155,NaN
3,2027946872758034525,Sun Mar 01 03:19:46 +0000 2026,474,Saldo e-wallet senilai total JUTAAN RUPIAH bua...,2027946872758034525,https://pbs.twimg.com/media/HCS2zD3acAAvMXb.jpg,NaN,in,NaN,20,2446,354,https://x.com/undefined/status/202794687275803...,69183155,NaN
4,2027934645879513534,Sun Mar 01 02:31:11 +0000 2026,1047,Iran akhirnya mengeluarkan pernyataan resmi te...,2027934645879513534,https://pbs.twimg.com/media/HCSroBKbsAAPsoe.jpg,NaN,in,NaN,28,212,165,https://x.com/undefined/status/202793464587951...,69183155,NaN

In [9]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 100.

In [10]:
df = df.copy()
df

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2027988901068177718,Sun Mar 01 06:06:46 +0000 2026,64,Iran membalas serangan AS-Israel dengan membom...,2027988901068177718,NaN,NaN,in,NaN,1,2,5,https://x.com/undefined/status/202798890106817...,69183155,NaN
1,2027973484236927204,Sun Mar 01 05:05:31 +0000 2026,64,Pemimpin tertinggi Iran Ali Khamenei dikabarka...,2027973484236927204,NaN,NaN,in,NaN,1,10,13,https://x.com/undefined/status/202797348423692...,69183155,NaN
2,2027946872758034525,Sun Mar 01 03:19:47 +0000 2026,176,Jangan lupa untuk ikutin syarat dan ketentuan ...,2027946875400429965,https://pbs.twimg.com/media/HCS27eGbcAAbpoj.jpg,detikcom,in,NaN,4,403,131,https://x.com/undefined/status/202794687540042...,69183155,NaN
3,2027946872758034525,Sun Mar 01 03:19:46 +0000 2026,474,Saldo e-wallet senilai total JUTAAN RUPIAH bua...,2027946872758034525,https://pbs.twimg.com/media/HCS2zD3acAAvMXb.jpg,NaN,in,NaN,20,2446,354,https://x.com/undefined/status/202794687275803...,69183155,NaN
4,2027934645879513534,Sun Mar 01 02:31:11 +0000 2026,1047,Iran akhirnya mengeluarkan pernyataan resmi te...,2027934645879513534,https://pbs.twimg.com/media/HCSroBKbsAAPsoe.jpg,NaN,in,NaN,28,212,165,https://x.com/undefined/status/202793464587951...,69183155,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2027387242486940059,Fri Feb 27 14:16:00 +0000 2026,46,Kurang lebih Rp 240 triliun uang beredar dari...,2027387242486940059,NaN,NaN,in,NaN,15,56,24,https://x.com/undefined/status/202738724248694...,69183155,NaN
96,2027383222070632673,Fri Feb 27 14:00:01 +0000 2026,109,Piton Raksasa Muncul di Tengah Banjir Bali War...,2027383222070632673,https://pbs.twimg.com/amplify_video_thumb/2027...,NaN,in,NaN,1,9,23,https://x.com/undefined/status/202738322207063...,69183155,NaN
97,2027368122211016784,Fri Feb 27 13:00:01 +0000 2026,113,Langgar Izin Tinggal DJ Asal China dan Dancer ...,2027368122211016784,https://pbs.twimg.com/amplify_video_thumb/2027...,NaN,in,NaN,1,6,30,https://x.com/undefined/status/202736812221101...,69183155,NaN
98,2027340247206592842,Fri Feb 27 11:09:15 +0000 2026,14,Jaksa Muda Intelijen (Jamintel) Kejaksaan Agun...,2027340247206592842,https://pbs.twimg.com/amplify_video_thumb/2027...,NaN,in,NaN,0,2,3,https://x.com/undefined/status/202734024720659...,69183155,NaN
99,2027318036189827561,Fri Feb 27 09:41:00 +0000 2026,12,Kasus penganiayaan bocah 13 tahun di Sukabumi ...,2027318036189827561,NaN,NaN,in,NaN,1,1,3,https://x.com/undefined/status/202731803618982...,69183155,NaN

In [11]:
#set agar data bisa dilihat dengan lebar kolom maksimal
pd.set_option('display.max_colwidth', None)

In [13]:
# lihat kolom full_text
df['full_text'].head(100)

0                                                                                                                                                                  Iran membalas serangan AS-Israel dengan membombardir pangkalan di kawasan Teluk. Langit Dubai jadi sepi dari pesawat. https://t.co/xs7tgVTkET
1                                                                                                                                                                Pemimpin tertinggi Iran Ali Khamenei dikabarkan tewas dalam serangan Israel Sabtu (28/2/2026). Ini profil Ali Khamenei. https://t.co/3m2RFHN6sq
2     Jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin e-wallet masing-masing 500 ribu rupiah! Yuk reply jawaban kamu di thread ini dan kasih emoji sebanyak-banyaknya! Semoga beruntung detikers!#GalaxyS26 #detikcomxSamsung #YouAndAICan #GalaxyAI https://t.co/MqxjVlm33X
3                                                       Saldo e-wallet senilai total JUTAAN RUPIAH buat kamu nih! Caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa! #GalaxyS26 #detikcomxSamsung #YouAndAICan #GalaxyAI @samsungID https://t.co/0w5f2WBB8t
4                                                                              Iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian Ali Khamenei dalam serangan Israel dan Amerika Serikat. Pemimpin Tertinggi Iran itu telah terkonfirmasi tewas. https://t.co/IgQ7HBxQLE https://t.co/eqpP4W1OUg
                                                                                                                                                         ...
95                                                                                                                     Kurang lebih Rp 240 triliun uang beredar dari Sabang sampai Merauke dan setiap per 12 hari setiap SPPG menerima sekitar Rp 500 juta kata Dadan. via @detikfinance https://t.co/xpxibN9xKA
96                                      Piton Raksasa Muncul di Tengah Banjir Bali Warga Dibuat Geger Pihak Badan Penanggulangan Bencana Daerah mengimbau masyarakat tetap waspada terhadap potensi bahaya banjir termasuk kemungkinan munculnya hewan liar dari habitat yang tergenang. https://t.co/9EGdQTjuNU
97                                                                      Langgar Izin Tinggal DJ Asal China dan Dancer Thailand Dideportasi Petugas menjelaskan keduanya diamankan saat berada di sebuah klub malam di kawasan Kuningan Jakarta Selatan. &gt;&gt; https://t.co/FTdbO0cZGX https://t.co/6j8g19v4i6
98        Jaksa Muda Intelijen (Jamintel) Kejaksaan Agung Reda Manthovani bicara aplikasi Jaga Desa untuk membimbing aparatur desa agar mengelola dana desa dengan baik. Menurutnya tata kekola keuangan dana desa yang baik adalah wujud mendukung program Asta Cita poin ke-6 Presiden https://t.co/5uk91BHeuE
99                                                                            Kasus penganiayaan bocah 13 tahun di Sukabumi melibatkan ibu tiri berstatus ASN Kemenag. TR ditetapkan tersangka gaji tetap dibayar hingga putusan hukum. Berikut deretan fakta-faktanya! Via @detikjabar_ https://t.co/FNd0WgTYIy
Name: full_text, Length: 100, dtype: object

In [15]:
#masukan kolom full_text ke dalam variabel baru
data_cleaning = df['full_text']
data_cleaning.head(50)

0                                                                                                                                                                  Iran membalas serangan AS-Israel dengan membombardir pangkalan di kawasan Teluk. Langit Dubai jadi sepi dari pesawat. https://t.co/xs7tgVTkET
1                                                                                                                                                                Pemimpin tertinggi Iran Ali Khamenei dikabarkan tewas dalam serangan Israel Sabtu (28/2/2026). Ini profil Ali Khamenei. https://t.co/3m2RFHN6sq
2     Jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin e-wallet masing-masing 500 ribu rupiah! Yuk reply jawaban kamu di thread ini dan kasih emoji sebanyak-banyaknya! Semoga beruntung detikers!#GalaxyS26 #detikcomxSamsung #YouAndAICan #GalaxyAI https://t.co/MqxjVlm33X
3                                                       Saldo e-wallet senilai total JUTAAN RUPIAH buat kamu nih! Caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa! #GalaxyS26 #detikcomxSamsung #YouAndAICan #GalaxyAI @samsungID https://t.co/0w5f2WBB8t
4                                                                              Iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian Ali Khamenei dalam serangan Israel dan Amerika Serikat. Pemimpin Tertinggi Iran itu telah terkonfirmasi tewas. https://t.co/IgQ7HBxQLE https://t.co/eqpP4W1OUg
5                                                                                         Presiden Amerika Serikat (AS) Donald Trump mengumumkan kematian Pemimpin Tertinggi Iran Ali Khamenei. Khamenei tewas dalam serangan AS dan Israel di Teheran. &gt;&gt; https://t.co/JSa4uY0MHz https://t.co/Z2neeC6WDG
6                                                                                                           Israel dan Amerika Serikat (AS) melakukan serangan besar-besaran ke wilayah Iran. Menteri Pertahanan Iran Amir Nasirzadeh dilaporkan tewas. &gt;&gt; https://t.co/iJIoTQC4EI https://t.co/YgW3HdZnwy
7                                                                                                                           Xiaomi 17 resmi keluar dari China dan meluncur global lewat peluncuran di Barcelona Spanyol. Ini harga dan spesifikasi lengkap Xiaomi 17 untuk pasar global. https://t.co/GV4Q6SQGxe
8                                                                                                                                                   Xiaomi 17 dan 17 Ultra resmi rilis 3 Maret 2026 di Indonesia usung kamera Leica 200 MP dengan teknologi LOFIC dan zoom hingga 400mm. https://t.co/nPpeeFKK11
9                                                                                                                                         Garda Revolusi Iran mengumumkan pasukannya telah menyerang pangkalan-pangkalan militer AS yang ada di Bahrain Qatar dan Uni Emirat Arab (UEA). https://t.co/bprrrFyu92
10                                                                                                                                            Rentetan ledakan mengguncang sejumlah negara Teluk Arab yang menjadi lokasi pangkalan militer AS setelah AS bersama Israel menyerang Iran. https://t.co/bprrrFyu92
11                                                                                                                          Militer Israel mendeteksi sejumlah rudal yang diluncurkan dari Iran ke wilayahnya pada Sabtu (28/2) setelah Tel Aviv menggempur Teheran dan wilayah lainnya. https://t.co/IUPMNdp0nQ
12                                                                                                                                                  Israel dan Amerika Serikat menyerang Iran lewat serangan udara terkoordinasi. Wilayah udara Iran langsung kosong dari pesawat sipil. https://t.co/f5MtxXyYor
13                                                                                                                       Otoritas Iran mengumumkan penutupan wilayah udara hingga pemberitahuan lebih lanjut setelah rentetan ledakan terdengar di ibu kota Teheran dan wilayah lainnya. https://t.co/U1sPdvuR1K
14                                                                          Selamat kepada @JuliansyahSap18! Kamu berhak mendapatkan 1 unit Samsung Galaxy S26 Follow terus @detikcom untuk hadiah menarik lainnya ya detikers! #GalaxyS26 #detikcomxSamsung #YouAndICan #GalaxyUnpacked https://t.co/xW1zIKyNrG
15                                                                                                                     Kurang lebih Rp 240 triliun uang beredar dari Sabang sampai Merauke dan setiap per 12 hari setiap SPPG menerima sekitar Rp 500 juta kata Dadan. via @detikfinance https://t.co/xpxibN9xKA
16                                      Piton Raksasa Muncul di Tengah Banjir Bali Warga Dibuat Geger Pihak Badan Penanggulangan Bencana Daerah mengimbau masyarakat tetap waspada terhadap potensi bahaya banjir termasuk kemungkinan munculnya hewan liar dari habitat yang tergenang. https://t.co/9EGdQTjuNU
17                                                                      Langgar Izin Tinggal DJ Asal China dan Dancer Thailand Dideportasi Petugas menjelaskan keduanya diamankan saat berada di sebuah klub malam di kawasan Kuningan Jakarta Selatan. &gt;&gt; https://t.co/FTdbO0cZGX https://t.co/6j8g19v4i6
18        Jaksa Muda Intelijen (Jamintel) Kejaksaan Agung Reda Manthovani bicara aplikasi Jaga Desa untuk membimbing aparatur desa agar mengelola dana desa dengan baik. Menurutnya tata kekola keuangan dana desa yang baik adalah wujud mendukung program Asta Cita poin ke-6 Presiden https://t.co/5uk91BHeuE
19                                                                            Kasus penganiayaan bocah 13 tahun di Sukabumi melibatkan ibu tiri berstatus ASN Kemenag. TR ditetapkan tersangka gaji tetap dibayar hingga putusan hukum. Berikut deretan fakta-faktanya! Via @detikjabar_ https://t.co/FNd0WgTYIy
20                                                                                                                                                                 Iran membalas serangan AS-Israel dengan membombardir pangkalan di kawasan Teluk. Langit Dubai jadi sepi dari pesawat. https://t.co/xs7tgVTkET
21                                                                                                                                                               Pemimpin tertinggi Iran Ali Khamenei dikabarkan tewas dalam serangan Israel Sabtu (28/2/2026). Ini profil Ali Khamenei. https://t.co/3m2RFHN6sq
22    Jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin e-wallet masing-masing 500 ribu rupiah! Yuk reply jawaban kamu di thread ini dan kasih emoji sebanyak-banyaknya! Semoga beruntung detikers!#GalaxyS26 #detikcomxSamsung #YouAndAICan #GalaxyAI https://t.co/MqxjVlm33X
23                                                      Saldo e-wallet senilai total JUTAAN RUPIAH buat kamu nih! Caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa! #GalaxyS26 #detikcomxSamsung #YouAndAICan #GalaxyAI @samsungID https://t.co/0w5f2WBB8t
24                                                                             Iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian Ali Khamenei dalam serangan Israel dan Amerika Serikat. Pemimpin Tertinggi Iran itu telah terkonfirmasi tewas. https://t.co/IgQ7HBxQLE https://t.co/eqpP4W1OUg
25                                                                                        Presiden Amerika Serikat (AS) Donald Trump mengumumkan kematian Pemimpin Tertinggi Iran Ali Khamenei. Khamenei tewas dalam serangan AS dan Israel di Teheran. &gt;&gt; https://t.co/JSa4uY0MHz https://t.co/Z2neeC6WDG
26                                                                                                          Israel dan Amerika Serikat (AS) melakukan serangan besar-besaran ke wilayah Iran. Menteri Pertahanan Iran Amir Nasirzadeh dilaporkan tewas. &gt;&gt; https://t.co/iJIoTQC4EI https://t.co/YgW3HdZnwy
27                                                                                                                          Xiaomi 17 resmi keluar dari China dan meluncur global lewat peluncuran di Barcelona Spanyol. Ini harga dan spesifikasi lengkap Xiaomi 17 untuk pasar global. https://t.co/GV4Q6SQGxe
28                                                                                                                                                  Xiaomi 17 dan 17 Ultra resmi rilis 3 Maret 2026 di Indonesia usung kamera Leica 200 MP dengan teknologi LOFIC dan zoom hingga 400mm. https://t.co/nPpeeFKK11
29                                                                                                                                        Garda Revolusi Iran mengumumkan pasukannya telah menyerang pangkalan-pangkalan militer AS yang ada di Bahrain Qatar dan Uni Emirat Arab (UEA). https://t.co/bprrrFyu92
30                                                                                                                                            Rentetan ledakan mengguncang sejumlah negara Teluk Arab yang menjadi lokasi pangkalan militer AS setelah AS bersama Israel menyerang Iran. https://t.co/bprrrFyu92
31                                                                                                                          Militer Israel mendeteksi sejumlah rudal yang diluncurkan dari Iran ke wilayahnya pada Sabtu (28/2) setelah Tel Aviv menggempur Teheran dan wilayah lainnya. https://t.co/IUPMNdp0nQ
32                                                                                                                                                  Israel dan Amerika Serikat menyerang Iran lewat serangan udara terkoordinasi. Wilayah udara Iran langsung kosong dari pesawat sipil. https://t.co/f5MtxXyYor
33                                                                                                                       Otoritas Iran mengumumkan penutupan wilayah udara hingga pemberitahuan lebih lanjut setelah rentetan ledakan terdengar di ibu kota Teheran dan wilayah lainnya. https://t.co/U1sPdvuR1K
34                                                                          Selamat kepada @JuliansyahSap18! Kamu berhak mendapatkan 1 unit Samsung Galaxy S26 Follow terus @detikcom untuk hadiah menarik lainnya ya detikers! #GalaxyS26 #detikcomxSamsung #YouAndICan #GalaxyUnpacked https://t.co/xW1zIKyNrG
35                                                                                                                     Kurang lebih Rp 240 triliun uang beredar dari Sabang sampai Merauke dan setiap per 12 hari setiap SPPG menerima sekitar Rp 500 juta kata Dadan. via @detikfinance https://t.co/xpxibN9xKA
36                                      Piton Raksasa Muncul di Tengah Banjir Bali Warga Dibuat Geger Pihak Badan Penanggulangan Bencana Daerah mengimbau masyarakat tetap waspada terhadap potensi bahaya banjir termasuk kemungkinan munculnya hewan liar dari habitat yang tergenang. https://t.co/9EGdQTjuNU
37                                                                      Langgar Izin Tinggal DJ Asal China dan Dancer Thailand Dideportasi Petugas menjelaskan keduanya diamankan saat berada di sebuah klub malam di kawasan Kuningan Jakarta Selatan. &gt;&gt; https://t.co/FTdbO0cZGX https://t.co/6j8g19v4i6
38        Jaksa Muda Intelijen (Jamintel) Kejaksaan Agung Reda Manthovani bicara aplikasi Jaga Desa untuk membimbing aparatur desa agar mengelola dana desa dengan baik. Menurutnya tata kekola keuangan dana desa yang baik adalah wujud mendukung program Asta Cita poin ke-6 Presiden https://t.co/5uk91BHeuE
39                                                                            Kasus penganiayaan bocah 13 tahun di Sukabumi melibatkan ibu tiri berstatus ASN Kemenag. TR ditetapkan tersangka gaji tetap dibayar hingga putusan hukum. Berikut deretan fakta-faktanya! Via @detikjabar_ https://t.co/FNd0WgTYIy
40                                                                                                                                                                 Iran membalas serangan AS-Israel dengan membombardir pangkalan di kawasan Teluk. Langit Dubai jadi sepi dari pesawat. https://t.co/xs7tgVTkET
41                                                                                                                                                               Pemimpin tertinggi Iran Ali Khamenei dikabarkan tewas dalam serangan Israel Sabtu (28/2/2026). Ini profil Ali Khamenei. https://t.co/3m2RFHN6sq
42    Jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin e-wallet masing-masing 500 ribu rupiah! Yuk reply jawaban kamu di thread ini dan kasih emoji sebanyak-banyaknya! Semoga beruntung detikers!#GalaxyS26 #detikcomxSamsung #YouAndAICan #GalaxyAI https://t.co/MqxjVlm33X
43                                                      Saldo e-wallet senilai total JUTAAN RUPIAH buat kamu nih! Caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa! #GalaxyS26 #detikcomxSamsung #YouAndAICan #GalaxyAI @samsungID https://t.co/0w5f2WBB8t
44                                                                             Iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian Ali Khamenei dalam serangan Israel dan Amerika Serikat. Pemimpin Tertinggi Iran itu telah terkonfirmasi tewas. https://t.co/IgQ7HBxQLE https://t.co/eqpP4W1OUg
45                                                                                        Presiden Amerika Serikat (AS) Donald Trump mengumumkan kematian Pemimpin Tertinggi Iran Ali Khamenei. Khamenei tewas dalam serangan AS dan Israel di Teheran. &gt;&gt; https://t.co/JSa4uY0MHz https://t.co/Z2neeC6WDG
46                                                                                                          Israel dan Amerika Serikat (AS) melakukan serangan besar-besaran ke wilayah Iran. Menteri Pertahanan Iran Amir Nasirzadeh dilaporkan tewas. &gt;&gt; https://t.co/iJIoTQC4EI https://t.co/YgW3HdZnwy
47                                                                                                                          Xiaomi 17 resmi keluar dari China dan meluncur global lewat peluncuran di Barcelona Spanyol. Ini harga dan spesifikasi lengkap Xiaomi 17 untuk pasar global. https://t.co/GV4Q6SQGxe
48                                                                                                                                                  Xiaomi 17 dan 17 Ultra resmi rilis 3 Maret 2026 di Indonesia usung kamera Leica 200 MP dengan teknologi LOFIC dan zoom hingga 400mm. https://t.co/nPpeeFKK11
49                                                                                                                                        Garda Revolusi Iran mengumumkan pasukannya telah menyerang pangkalan-pangkalan militer AS yang ada di Bahrain Qatar dan Uni Emirat Arab (UEA). https://t.co/bprrrFyu92
Name: full_text, dtype: object

Lowercasing

In [16]:
df['content_clean'] = df['full_text'].str.lower()
df['content_clean'].head(50)

0                                                                                                                                                                  iran membalas serangan as-israel dengan membombardir pangkalan di kawasan teluk. langit dubai jadi sepi dari pesawat. https://t.co/xs7tgvtket
1                                                                                                                                                                pemimpin tertinggi iran ali khamenei dikabarkan tewas dalam serangan israel sabtu (28/2/2026). ini profil ali khamenei. https://t.co/3m2rfhn6sq
2     jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin e-wallet masing-masing 500 ribu rupiah! yuk reply jawaban kamu di thread ini dan kasih emoji sebanyak-banyaknya! semoga beruntung detikers!#galaxys26 #detikcomxsamsung #youandaican #galaxyai https://t.co/mqxjvlm33x
3                                                       saldo e-wallet senilai total jutaan rupiah buat kamu nih! caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa! #galaxys26 #detikcomxsamsung #youandaican #galaxyai @samsungid https://t.co/0w5f2wbb8t
4                                                                              iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian ali khamenei dalam serangan israel dan amerika serikat. pemimpin tertinggi iran itu telah terkonfirmasi tewas. https://t.co/igq7hbxqle https://t.co/eqpp4w1oug
5                                                                                         presiden amerika serikat (as) donald trump mengumumkan kematian pemimpin tertinggi iran ali khamenei. khamenei tewas dalam serangan as dan israel di teheran. &gt;&gt; https://t.co/jsa4uy0mhz https://t.co/z2neec6wdg
6                                                                                                           israel dan amerika serikat (as) melakukan serangan besar-besaran ke wilayah iran. menteri pertahanan iran amir nasirzadeh dilaporkan tewas. &gt;&gt; https://t.co/ijiotqc4ei https://t.co/ygw3hdznwy
7                                                                                                                           xiaomi 17 resmi keluar dari china dan meluncur global lewat peluncuran di barcelona spanyol. ini harga dan spesifikasi lengkap xiaomi 17 untuk pasar global. https://t.co/gv4q6sqgxe
8                                                                                                                                                   xiaomi 17 dan 17 ultra resmi rilis 3 maret 2026 di indonesia usung kamera leica 200 mp dengan teknologi lofic dan zoom hingga 400mm. https://t.co/nppeefkk11
9                                                                                                                                         garda revolusi iran mengumumkan pasukannya telah menyerang pangkalan-pangkalan militer as yang ada di bahrain qatar dan uni emirat arab (uea). https://t.co/bprrrfyu92
10                                                                                                                                            rentetan ledakan mengguncang sejumlah negara teluk arab yang menjadi lokasi pangkalan militer as setelah as bersama israel menyerang iran. https://t.co/bprrrfyu92
11                                                                                                                          militer israel mendeteksi sejumlah rudal yang diluncurkan dari iran ke wilayahnya pada sabtu (28/2) setelah tel aviv menggempur teheran dan wilayah lainnya. https://t.co/iupmndp0nq
12                                                                                                                                                  israel dan amerika serikat menyerang iran lewat serangan udara terkoordinasi. wilayah udara iran langsung kosong dari pesawat sipil. https://t.co/f5mtxxyyor
13                                                                                                                       otoritas iran mengumumkan penutupan wilayah udara hingga pemberitahuan lebih lanjut setelah rentetan ledakan terdengar di ibu kota teheran dan wilayah lainnya. https://t.co/u1spdvur1k
14                                                                          selamat kepada @juliansyahsap18! kamu berhak mendapatkan 1 unit samsung galaxy s26 follow terus @detikcom untuk hadiah menarik lainnya ya detikers! #galaxys26 #detikcomxsamsung #youandican #galaxyunpacked https://t.co/xw1zikynrg
15                                                                                                                     kurang lebih rp 240 triliun uang beredar dari sabang sampai merauke dan setiap per 12 hari setiap sppg menerima sekitar rp 500 juta kata dadan. via @detikfinance https://t.co/xpxibn9xka
16                                      piton raksasa muncul di tengah banjir bali warga dibuat geger pihak badan penanggulangan bencana daerah mengimbau masyarakat tetap waspada terhadap potensi bahaya banjir termasuk kemungkinan munculnya hewan liar dari habitat yang tergenang. https://t.co/9egdqtjunu
17                                                                      langgar izin tinggal dj asal china dan dancer thailand dideportasi petugas menjelaskan keduanya diamankan saat berada di sebuah klub malam di kawasan kuningan jakarta selatan. &gt;&gt; https://t.co/ftdbo0czgx https://t.co/6j8g19v4i6
18        jaksa muda intelijen (jamintel) kejaksaan agung reda manthovani bicara aplikasi jaga desa untuk membimbing aparatur desa agar mengelola dana desa dengan baik. menurutnya tata kekola keuangan dana desa yang baik adalah wujud mendukung program asta cita poin ke-6 presiden https://t.co/5uk91bheue
19                                                                            kasus penganiayaan bocah 13 tahun di sukabumi melibatkan ibu tiri berstatus asn kemenag. tr ditetapkan tersangka gaji tetap dibayar hingga putusan hukum. berikut deretan fakta-faktanya! via @detikjabar_ https://t.co/fnd0wgtyiy
20                                                                                                                                                                 iran membalas serangan as-israel dengan membombardir pangkalan di kawasan teluk. langit dubai jadi sepi dari pesawat. https://t.co/xs7tgvtket
21                                                                                                                                                               pemimpin tertinggi iran ali khamenei dikabarkan tewas dalam serangan israel sabtu (28/2/2026). ini profil ali khamenei. https://t.co/3m2rfhn6sq
22    jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin e-wallet masing-masing 500 ribu rupiah! yuk reply jawaban kamu di thread ini dan kasih emoji sebanyak-banyaknya! semoga beruntung detikers!#galaxys26 #detikcomxsamsung #youandaican #galaxyai https://t.co/mqxjvlm33x
23                                                      saldo e-wallet senilai total jutaan rupiah buat kamu nih! caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa! #galaxys26 #detikcomxsamsung #youandaican #galaxyai @samsungid https://t.co/0w5f2wbb8t
24                                                                             iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian ali khamenei dalam serangan israel dan amerika serikat. pemimpin tertinggi iran itu telah terkonfirmasi tewas. https://t.co/igq7hbxqle https://t.co/eqpp4w1oug
25                                                                                        presiden amerika serikat (as) donald trump mengumumkan kematian pemimpin tertinggi iran ali khamenei. khamenei tewas dalam serangan as dan israel di teheran. &gt;&gt; https://t.co/jsa4uy0mhz https://t.co/z2neec6wdg
26                                                                                                          israel dan amerika serikat (as) melakukan serangan besar-besaran ke wilayah iran. menteri pertahanan iran amir nasirzadeh dilaporkan tewas. &gt;&gt; https://t.co/ijiotqc4ei https://t.co/ygw3hdznwy
27                                                                                                                          xiaomi 17 resmi keluar dari china dan meluncur global lewat peluncuran di barcelona spanyol. ini harga dan spesifikasi lengkap xiaomi 17 untuk pasar global. https://t.co/gv4q6sqgxe
28                                                                                                                                                  xiaomi 17 dan 17 ultra resmi rilis 3 maret 2026 di indonesia usung kamera leica 200 mp dengan teknologi lofic dan zoom hingga 400mm. https://t.co/nppeefkk11
29                                                                                                                                        garda revolusi iran mengumumkan pasukannya telah menyerang pangkalan-pangkalan militer as yang ada di bahrain qatar dan uni emirat arab (uea). https://t.co/bprrrfyu92
30                                                                                                                                            rentetan ledakan mengguncang sejumlah negara teluk arab yang menjadi lokasi pangkalan militer as setelah as bersama israel menyerang iran. https://t.co/bprrrfyu92
31                                                                                                                          militer israel mendeteksi sejumlah rudal yang diluncurkan dari iran ke wilayahnya pada sabtu (28/2) setelah tel aviv menggempur teheran dan wilayah lainnya. https://t.co/iupmndp0nq
32                                                                                                                                                  israel dan amerika serikat menyerang iran lewat serangan udara terkoordinasi. wilayah udara iran langsung kosong dari pesawat sipil. https://t.co/f5mtxxyyor
33                                                                                                                       otoritas iran mengumumkan penutupan wilayah udara hingga pemberitahuan lebih lanjut setelah rentetan ledakan terdengar di ibu kota teheran dan wilayah lainnya. https://t.co/u1spdvur1k
34                                                                          selamat kepada @juliansyahsap18! kamu berhak mendapatkan 1 unit samsung galaxy s26 follow terus @detikcom untuk hadiah menarik lainnya ya detikers! #galaxys26 #detikcomxsamsung #youandican #galaxyunpacked https://t.co/xw1zikynrg
35                                                                                                                     kurang lebih rp 240 triliun uang beredar dari sabang sampai merauke dan setiap per 12 hari setiap sppg menerima sekitar rp 500 juta kata dadan. via @detikfinance https://t.co/xpxibn9xka
36                                      piton raksasa muncul di tengah banjir bali warga dibuat geger pihak badan penanggulangan bencana daerah mengimbau masyarakat tetap waspada terhadap potensi bahaya banjir termasuk kemungkinan munculnya hewan liar dari habitat yang tergenang. https://t.co/9egdqtjunu
37                                                                      langgar izin tinggal dj asal china dan dancer thailand dideportasi petugas menjelaskan keduanya diamankan saat berada di sebuah klub malam di kawasan kuningan jakarta selatan. &gt;&gt; https://t.co/ftdbo0czgx https://t.co/6j8g19v4i6
38        jaksa muda intelijen (jamintel) kejaksaan agung reda manthovani bicara aplikasi jaga desa untuk membimbing aparatur desa agar mengelola dana desa dengan baik. menurutnya tata kekola keuangan dana desa yang baik adalah wujud mendukung program asta cita poin ke-6 presiden https://t.co/5uk91bheue
39                                                                            kasus penganiayaan bocah 13 tahun di sukabumi melibatkan ibu tiri berstatus asn kemenag. tr ditetapkan tersangka gaji tetap dibayar hingga putusan hukum. berikut deretan fakta-faktanya! via @detikjabar_ https://t.co/fnd0wgtyiy
40                                                                                                                                                                 iran membalas serangan as-israel dengan membombardir pangkalan di kawasan teluk. langit dubai jadi sepi dari pesawat. https://t.co/xs7tgvtket
41                                                                                                                                                               pemimpin tertinggi iran ali khamenei dikabarkan tewas dalam serangan israel sabtu (28/2/2026). ini profil ali khamenei. https://t.co/3m2rfhn6sq
42    jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin e-wallet masing-masing 500 ribu rupiah! yuk reply jawaban kamu di thread ini dan kasih emoji sebanyak-banyaknya! semoga beruntung detikers!#galaxys26 #detikcomxsamsung #youandaican #galaxyai https://t.co/mqxjvlm33x
43                                                      saldo e-wallet senilai total jutaan rupiah buat kamu nih! caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa! #galaxys26 #detikcomxsamsung #youandaican #galaxyai @samsungid https://t.co/0w5f2wbb8t
44                                                                             iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian ali khamenei dalam serangan israel dan amerika serikat. pemimpin tertinggi iran itu telah terkonfirmasi tewas. https://t.co/igq7hbxqle https://t.co/eqpp4w1oug
45                                                                                        presiden amerika serikat (as) donald trump mengumumkan kematian pemimpin tertinggi iran ali khamenei. khamenei tewas dalam serangan as dan israel di teheran. &gt;&gt; https://t.co/jsa4uy0mhz https://t.co/z2neec6wdg
46                                                                                                          israel dan amerika serikat (as) melakukan serangan besar-besaran ke wilayah iran. menteri pertahanan iran amir nasirzadeh dilaporkan tewas. &gt;&gt; https://t.co/ijiotqc4ei https://t.co/ygw3hdznwy
47                                                                                                                          xiaomi 17 resmi keluar dari china dan meluncur global lewat peluncuran di barcelona spanyol. ini harga dan spesifikasi lengkap xiaomi 17 untuk pasar global. https://t.co/gv4q6sqgxe
48                                                                                                                                                  xiaomi 17 dan 17 ultra resmi rilis 3 maret 2026 di indonesia usung kamera leica 200 mp dengan teknologi lofic dan zoom hingga 400mm. https://t.co/nppeefkk11
49                                                                                                                                        garda revolusi iran mengumumkan pasukannya telah menyerang pangkalan-pangkalan militer as yang ada di bahrain qatar dan uni emirat arab (uea). https://t.co/bprrrfyu92
Name: content_clean, dtype: object

Menghapus Tanda Baca

In [17]:
df['content_clean'].str.strip()

0                                                                                                                                                                  iran membalas serangan as-israel dengan membombardir pangkalan di kawasan teluk. langit dubai jadi sepi dari pesawat. https://t.co/xs7tgvtket
1                                                                                                                                                                pemimpin tertinggi iran ali khamenei dikabarkan tewas dalam serangan israel sabtu (28/2/2026). ini profil ali khamenei. https://t.co/3m2rfhn6sq
2     jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin e-wallet masing-masing 500 ribu rupiah! yuk reply jawaban kamu di thread ini dan kasih emoji sebanyak-banyaknya! semoga beruntung detikers!#galaxys26 #detikcomxsamsung #youandaican #galaxyai https://t.co/mqxjvlm33x
3                                                       saldo e-wallet senilai total jutaan rupiah buat kamu nih! caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa! #galaxys26 #detikcomxsamsung #youandaican #galaxyai @samsungid https://t.co/0w5f2wbb8t
4                                                                              iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian ali khamenei dalam serangan israel dan amerika serikat. pemimpin tertinggi iran itu telah terkonfirmasi tewas. https://t.co/igq7hbxqle https://t.co/eqpp4w1oug
                                                                                                                                                         ...
95                                                                                                                     kurang lebih rp 240 triliun uang beredar dari sabang sampai merauke dan setiap per 12 hari setiap sppg menerima sekitar rp 500 juta kata dadan. via @detikfinance https://t.co/xpxibn9xka
96                                      piton raksasa muncul di tengah banjir bali warga dibuat geger pihak badan penanggulangan bencana daerah mengimbau masyarakat tetap waspada terhadap potensi bahaya banjir termasuk kemungkinan munculnya hewan liar dari habitat yang tergenang. https://t.co/9egdqtjunu
97                                                                      langgar izin tinggal dj asal china dan dancer thailand dideportasi petugas menjelaskan keduanya diamankan saat berada di sebuah klub malam di kawasan kuningan jakarta selatan. &gt;&gt; https://t.co/ftdbo0czgx https://t.co/6j8g19v4i6
98        jaksa muda intelijen (jamintel) kejaksaan agung reda manthovani bicara aplikasi jaga desa untuk membimbing aparatur desa agar mengelola dana desa dengan baik. menurutnya tata kekola keuangan dana desa yang baik adalah wujud mendukung program asta cita poin ke-6 presiden https://t.co/5uk91bheue
99                                                                            kasus penganiayaan bocah 13 tahun di sukabumi melibatkan ibu tiri berstatus asn kemenag. tr ditetapkan tersangka gaji tetap dibayar hingga putusan hukum. berikut deretan fakta-faktanya! via @detikjabar_ https://t.co/fnd0wgtyiy
Name: content_clean, Length: 100, dtype: object

In [19]:
df['content_clean'].str.replace('[^\w\s]','',regex=True).head(100)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_402/3525884728.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'].str.replace('[^\w\s]','',regex=True).head(100)

0                                                                                                                                                             iran membalas serangan asisrael dengan membombardir pangkalan di kawasan teluk langit dubai jadi sepi dari pesawat httpstcoxs7tgvtket
1                                                                                                                                                              pemimpin tertinggi iran ali khamenei dikabarkan tewas dalam serangan israel sabtu 2822026 ini profil ali khamenei httpstco3m2rfhn6sq
2       jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin ewallet masingmasing 500 ribu rupiah yuk reply jawaban kamu di thread ini dan kasih emoji sebanyakbanyaknya semoga beruntung detikersgalaxys26 detikcomxsamsung youandaican galaxyai httpstcomqxjvlm33x
3                                                       saldo ewallet senilai total jutaan rupiah buat kamu nih caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa galaxys26 detikcomxsamsung youandaican galaxyai samsungid httpstco0w5f2wbb8t
4                                                                             iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian ali khamenei dalam serangan israel dan amerika serikat pemimpin tertinggi iran itu telah terkonfirmasi tewas httpstcoigq7hbxqle httpstcoeqpp4w1oug
                                                                                                                                                  ...
95                                                                                                               kurang lebih rp 240 triliun uang beredar dari sabang sampai merauke dan setiap per 12 hari setiap sppg menerima sekitar rp 500 juta kata dadan via detikfinance httpstcoxpxibn9xka
96                               piton raksasa muncul di tengah banjir bali warga dibuat geger pihak badan penanggulangan bencana daerah mengimbau masyarakat tetap waspada terhadap potensi bahaya banjir termasuk kemungkinan munculnya hewan liar dari habitat yang tergenang httpstco9egdqtjunu
97                                                                        langgar izin tinggal dj asal china dan dancer thailand dideportasi petugas menjelaskan keduanya diamankan saat berada di sebuah klub malam di kawasan kuningan jakarta selatan gtgt httpstcoftdbo0czgx httpstco6j8g19v4i6
98    jaksa muda intelijen jamintel kejaksaan agung reda manthovani bicara aplikasi jaga desa untuk membimbing aparatur desa agar mengelola dana desa dengan baik menurutnya tata kekola keuangan dana desa yang baik adalah wujud mendukung program asta cita poin ke6 presiden httpstco5uk91bheue
99                                                                         kasus penganiayaan bocah 13 tahun di sukabumi melibatkan ibu tiri berstatus asn kemenag tr ditetapkan tersangka gaji tetap dibayar hingga putusan hukum berikut deretan faktafaktanya via detikjabar_ httpstcofnd0wgtyiy
Name: content_clean, Length: 100, dtype: object

Mengubah Punctuation

In [20]:
df['content_clean'].str.replace('[^\w\s]','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_402/3208373244.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'].str.replace('[^\w\s]','',regex=True)

0                                                                                                                                                             iran membalas serangan asisrael dengan membombardir pangkalan di kawasan teluk langit dubai jadi sepi dari pesawat httpstcoxs7tgvtket
1                                                                                                                                                              pemimpin tertinggi iran ali khamenei dikabarkan tewas dalam serangan israel sabtu 2822026 ini profil ali khamenei httpstco3m2rfhn6sq
2       jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin ewallet masingmasing 500 ribu rupiah yuk reply jawaban kamu di thread ini dan kasih emoji sebanyakbanyaknya semoga beruntung detikersgalaxys26 detikcomxsamsung youandaican galaxyai httpstcomqxjvlm33x
3                                                       saldo ewallet senilai total jutaan rupiah buat kamu nih caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa galaxys26 detikcomxsamsung youandaican galaxyai samsungid httpstco0w5f2wbb8t
4                                                                             iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian ali khamenei dalam serangan israel dan amerika serikat pemimpin tertinggi iran itu telah terkonfirmasi tewas httpstcoigq7hbxqle httpstcoeqpp4w1oug
                                                                                                                                                  ...
95                                                                                                               kurang lebih rp 240 triliun uang beredar dari sabang sampai merauke dan setiap per 12 hari setiap sppg menerima sekitar rp 500 juta kata dadan via detikfinance httpstcoxpxibn9xka
96                               piton raksasa muncul di tengah banjir bali warga dibuat geger pihak badan penanggulangan bencana daerah mengimbau masyarakat tetap waspada terhadap potensi bahaya banjir termasuk kemungkinan munculnya hewan liar dari habitat yang tergenang httpstco9egdqtjunu
97                                                                        langgar izin tinggal dj asal china dan dancer thailand dideportasi petugas menjelaskan keduanya diamankan saat berada di sebuah klub malam di kawasan kuningan jakarta selatan gtgt httpstcoftdbo0czgx httpstco6j8g19v4i6
98    jaksa muda intelijen jamintel kejaksaan agung reda manthovani bicara aplikasi jaga desa untuk membimbing aparatur desa agar mengelola dana desa dengan baik menurutnya tata kekola keuangan dana desa yang baik adalah wujud mendukung program asta cita poin ke6 presiden httpstco5uk91bheue
99                                                                         kasus penganiayaan bocah 13 tahun di sukabumi melibatkan ibu tiri berstatus asn kemenag tr ditetapkan tersangka gaji tetap dibayar hingga putusan hukum berikut deretan faktafaktanya via detikjabar_ httpstcofnd0wgtyiy
Name: content_clean, Length: 100, dtype: object

Buat Fungsi

In [21]:
def clean_data(text,column_name):
    df['content_clean'] = df[column_name].str.lower()
    df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)
    return df

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_402/1186799193.py:3: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)

In [22]:
df = clean_data(df, 'full_text')

print(df[['full_text', 'content_clean']])

                                                                                                                                                                                                                                                                                                     full_text  \
0                                                                                                                                                                Iran membalas serangan AS-Israel dengan membombardir pangkalan di kawasan Teluk. Langit Dubai jadi sepi dari pesawat. https://t.co/xs7tgVTkET
1                                                                                                                                                              Pemimpin tertinggi Iran Ali Khamenei dikabarkan tewas dalam serangan Israel Sabtu (28/2/2026). Ini profil Ali Khamenei. https://t.co/3m2RFHN6sq
2   Jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin e-wallet masing-masing 500 ribu rupiah! Yuk reply jawaban kamu di thread ini dan kasih emoji sebanyak-banyaknya! Semoga beruntung detikers!#GalaxyS26 #detikcomxSamsung #YouAndAICan #GalaxyAI https://t.co/MqxjVlm33X
3                                                     Saldo e-wallet senilai total JUTAAN RUPIAH buat kamu nih! Caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa! #GalaxyS26 #detikcomxSamsung #YouAndAICan #GalaxyAI @samsungID https://t.co/0w5f2WBB8t
4                                                                            Iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian Ali Khamenei dalam serangan Israel dan Amerika Serikat. Pemimpin Tertinggi Iran itu telah terkonfirmasi tewas. https://t.co/IgQ7HBxQLE https://t.co/eqpP4W1OUg
..                                                                                                                                                                                                                                                                                                         ...
95                                                                                                                   Kurang lebih Rp 240 triliun uang beredar dari Sabang sampai Merauke dan setiap per 12 hari setiap SPPG menerima sekitar Rp 500 juta kata Dadan. via @detikfinance https://t.co/xpxibN9xKA
96                                    Piton Raksasa Muncul di Tengah Banjir Bali Warga Dibuat Geger Pihak Badan Penanggulangan Bencana Daerah mengimbau masyarakat tetap waspada terhadap potensi bahaya banjir termasuk kemungkinan munculnya hewan liar dari habitat yang tergenang. https://t.co/9EGdQTjuNU
97                                                                    Langgar Izin Tinggal DJ Asal China dan Dancer Thailand Dideportasi Petugas menjelaskan keduanya diamankan saat berada di sebuah klub malam di kawasan Kuningan Jakarta Selatan. &gt;&gt; https://t.co/FTdbO0cZGX https://t.co/6j8g19v4i6
98      Jaksa Muda Intelijen (Jamintel) Kejaksaan Agung Reda Manthovani bicara aplikasi Jaga Desa untuk membimbing aparatur desa agar mengelola dana desa dengan baik. Menurutnya tata kekola keuangan dana desa yang baik adalah wujud mendukung program Asta Cita poin ke-6 Presiden https://t.co/5uk91BHeuE
99                                                                          Kasus penganiayaan bocah 13 tahun di Sukabumi melibatkan ibu tiri berstatus ASN Kemenag. TR ditetapkan tersangka gaji tetap dibayar hingga putusan hukum. Berikut deretan fakta-faktanya! Via @detikjabar_ https://t.co/FNd0WgTYIy

                                                                                                                                                                                                                                                                                    content_clean
0                                                                                                                                                           iran membalas serangan asisrael dengan membombardir pangkalan di kawasan teluk langit dubai jadi sepi dari pesawat httpstcoxs7tgvtket
1                                                                                                                                                            pemimpin tertinggi iran ali khamenei dikabarkan tewas dalam serangan israel sabtu 2822026 ini profil ali khamenei httpstco3m2rfhn6sq
2     jangan lupa untuk ikutin syarat dan ketentuan di bawah ini supaya kamu bisa dapetin ewallet masingmasing 500 ribu rupiah yuk reply jawaban kamu di thread ini dan kasih emoji sebanyakbanyaknya semoga beruntung detikersgalaxys26 detikcomxsamsung youandaican galaxyai httpstcomqxjvlm33x
3                                                     saldo ewallet senilai total jutaan rupiah buat kamu nih caranya jawab pertanyaan di bawah ini dan ikuti mekanisme yang akan detikcom share di next tweet yaaaa galaxys26 detikcomxsamsung youandaican galaxyai samsungid httpstco0w5f2wbb8t
4                                                                           iran akhirnya mengeluarkan pernyataan resmi terkait kabar kematian ali khamenei dalam serangan israel dan amerika serikat pemimpin tertinggi iran itu telah terkonfirmasi tewas httpstcoigq7hbxqle httpstcoeqpp4w1oug
..                                                                                                                                                                                                                                                                                            ...
95                                                                                                             kurang lebih rp 240 triliun uang beredar dari sabang sampai merauke dan setiap per 12 hari setiap sppg menerima sekitar rp 500 juta kata dadan via detikfinance httpstcoxpxibn9xka
96                             piton raksasa muncul di tengah banjir bali warga dibuat geger pihak badan penanggulangan bencana daerah mengimbau masyarakat tetap waspada terhadap potensi bahaya banjir termasuk kemungkinan munculnya hewan liar dari habitat yang tergenang httpstco9egdqtjunu
97                                                                      langgar izin tinggal dj asal china dan dancer thailand dideportasi petugas menjelaskan keduanya diamankan saat berada di sebuah klub malam di kawasan kuningan jakarta selatan gtgt httpstcoftdbo0czgx httpstco6j8g19v4i6
98  jaksa muda intelijen jamintel kejaksaan agung reda manthovani bicara aplikasi jaga desa untuk membimbing aparatur desa agar mengelola dana desa dengan baik menurutnya tata kekola keuangan dana desa yang baik adalah wujud mendukung program asta cita poin ke6 presiden httpstco5uk91bheue
99                                                                       kasus penganiayaan bocah 13 tahun di sukabumi melibatkan ibu tiri berstatus asn kemenag tr ditetapkan tersangka gaji tetap dibayar hingga putusan hukum berikut deretan faktafaktanya via detikjabar_ httpstcofnd0wgtyiy

[100 rows x 2 columns]

Import Library Spacy

In [23]:
#import library spacy
import spacy

In [24]:
#load model spacy untuk text processing
nlp = spacy.load('en_core_web_sm')
phrase = df.loc[1, 'content_clean']
phrase

'pemimpin tertinggi iran ali khamenei dikabarkan tewas dalam serangan israel sabtu 2822026 ini profil ali khamenei httpstco3m2rfhn6sq'

In [25]:
doc = nlp(phrase)
doc

pemimpin tertinggi iran ali khamenei dikabarkan tewas dalam serangan israel sabtu 2822026 ini profil ali khamenei httpstco3m2rfhn6sq

Membuat Tokenization

In [26]:
[token for token in doc]

[pemimpin,
 tertinggi,
 iran,
 ali,
 khamenei,
 dikabarkan,
 tewas,
 dalam,
 serangan,
 israel,
 sabtu,
 2822026,
 ini,
 profil,
 ali,
 khamenei,
 httpstco3m2rfhn6sq]

Lemmatization

In [27]:
[token.lemma_ for token in doc if not token.is_stop]

['pemimpin',
 'tertinggi',
 'iran',
 'ali',
 'khamenei',
 'dikabarkan',
 'tewa',
 'dalam',
 'serangan',
 'israel',
 'sabtu',
 '2822026',
 'ini',
 'profil',
 'ali',
 'khamenei',
 'httpstco3m2rfhn6sq']